
channels:
  - conda-forge
dependencies:
  - gdal=3.*
  - numpy=1.*
  - proj=7.*
  - python=3.7
  - matplotlib==3.*
  - pandas==1.*
  - scipy==1.*
  - shapely==1.*
  - geopandas==0.8.*
  - pip
  - pip:
      - apispec==2.0.2
      - flask==1.1.1
      - flask-apispec==0.8
      - flask-cors==3.0
      - flask-login==0.4
      - gsconfig-py3==1.0
      - owslib==0.18.*
      - simplejson==3.*
      - webargs==6.1

