channels:
  - conda-forge
dependencies:
  - gdal=3.*
  - numpy=1.*
  - proj=9.*
  - python=3.*
  - matplotlib==3.*
  - scipy==1.*
  - rasterio=1.3.*
  - geopandas==0.14.*
  - rasterstats
  - uwsgi
  - pip
  - pip:
      - uwsgi
      - flask
      - flask-apispec==0.11.4
      - flask-cors==4.0
      - flask-login==0.6.3
      - gsconfig-py3==1.*
      - rasterstats
      - owslib==0.18.*
      - simplejson==3.*
      - webargs==6.1
