name: heatstress
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - boost-cpp=1.72.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.24
  - cairo=1.16.0
  - certifi=2020.6.20
  - cfitsio=3.470
  - curl=7.71.1
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - freexl=1.0.5
  - gdal=3.1.1
  - geos=3.8.1
  - geotiff=1.6.0
  - giflib=5.2.1
  - glib=2.65.0
  - hdf4=4.2.13
  - hdf5=1.10.6
  - icu=64.2
  - intel-openmp=2020.1
  - jpeg=9d
  - json-c=0.13.1
  - kealib=1.4.13
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgdal=3.1.1
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.7.4
  - libpng=1.6.37
  - libpq=12.2
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.14
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - pcre=8.44
  - pip=20.1.1
  - pixman=0.38.0
  - poppler=0.89.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - proj=7.0.0
  - python=3.7.7
  - python_abi=3.7
  - readline=8.0
  - setuptools=47.3.1
  - sqlite=3.32.3
  - tbb=2020.0
  - tiledb=2.0.5
  - tk=8.6.10
  - wheel=0.34.2
  - xerces-c=3.2.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - apispec==2.0.2
    - attrs==19.3.0
    - backcall==0.2.0
    - bleach==3.1.5
    - chardet==3.0.4
    - click==6.7
    - click-plugins==1.1.1
    - cligj==0.5.0
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - descartes==1.1.0
    - entrypoints==0.3
    - fiona==1.8.13.post1
    - flask==1.1.1
    - flask-apispec==0.8.3
    - flask-cors==3.0.8
    - flask-login==0.4.1
    - geopandas==0.8.0
    - gsconfig-py3==1.0.8
    - idna==2.10
    - importlib-metadata==1.7.0
    - ipykernel==5.3.1
    - ipython==7.16.1
    - ipython-genutils==0.2.0
    - itsdangerous==0.24
    - jedi==0.17.1
    - jinja2==2.10.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.5
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - marshmallow==3.2.1
    - matplotlib==3.2.2
    - mistune==0.8.4
    - munch==2.5.0
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.0.3
    - owslib==0.18.0
    - packaging==20.4
    - pandas==1.0.5
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyproj==2.6.1.post1
    - pyrsistent==0.16.0
    - python-dateutil==2.7.3
    - pytz==2018.5
    - pyzmq==19.0.1
    - requests==2.24.0
    - scipy==1.5.1
    - send2trash==1.5.0
    - shapely==1.7.0
    - simplejson==3.17.0
    - six==1.11.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.4
    - traitlets==4.3.3
    - urllib3==1.25.9
    - wcwidth==0.2.5
    - webargs==6.1.0
    - webencodings==0.5.1
    - werkzeug==0.15.0
    - zipp==3.1.0
prefix: /home/ioanna/miniconda3/envs/heatstress

